# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [4]:
import numpy as np

2. Create a null vector of size 10 

In [6]:
nullVctr = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [46]:
rangeVctr = np.arange(10,49)

4. Find the shape of previous array in question 3

In [12]:
print('shape of array ', rangeVctr.shape)

shape of array  (39,)


5. Print the type of the previous array in question 3

In [17]:
print(rangeVctr.dtype)

int32


6. Print the numpy version and the configuration


In [21]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/HP/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C

7. Print the dimension of the array in question 3


In [22]:
print(rangeVctr.ndim)

1


8. Create a boolean array with all the True values

In [31]:
print('Boolean array with true values : ' , np.ones(10, dtype=bool))


Boolean array with true values :  [ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [41]:
print(np.ones((2,2)))
# print([[0]*2]*2)

[[1. 1.]
 [1. 1.]]


10. Create a three dimensional array



In [42]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [49]:
rangeVctr = np.arange(10,49)
print('vector : ', rangeVctr)
print('Reversed vector : ', np.flip(rangeVctr))

vector :  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
Reversed vector :  [48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [50]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [54]:
print('3x3 Identity matrix : ')
print( np.identity(3))

3x3 Identity matrix : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [61]:
arr = np.array([1, 2, 3, 4, 5])
floatArry = arr.astype('float64')
print(floatArry.dtype)

float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [70]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
print(np.multiply(arr1, arr2))
#print(arr1 * arr2)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [77]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

print((arr1 == arr2).all())

False


17. Extract all odd numbers from arr with values(0-9)

In [89]:
oddArr = np.arange(10)[np.arange(10) % 2 ==1]
print('Odd numbers : ' , oddArr)

Odd numbers :  [1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [107]:
x = np.arange(10)

x[x % 2 == 1] = -1
print(x)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [115]:
x = np.arange(10)
x [ (x > 4) & (x < 9)] = 12
print(x)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [131]:
x = np.ones((7,7))
x[1:-1 , 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [135]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
print(np.where(arr2d == 5,12, arr2d))

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [174]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                  [[7, 8, 9], [10, 11, 12]]])

arr3d[0,:-1] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [217]:
twoD = np.arange(10).reshape(2,5)
print('2-D array : ' , twoD)
print('1st 1-D array' , twoD[0])


2-D array :  [[0 1 2 3 4]
 [5 6 7 8 9]]
1st 1-D array [0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [219]:
twoD = np.arange(10).reshape(2,5)
print('2-D array : ' , twoD)
print('2nd 1-D array' , twoD[1])

2-D array :  [[0 1 2 3 4]
 [5 6 7 8 9]]
2nd 1-D array [5 6 7 8 9]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [230]:
twoD = np.arange(10).reshape(2,5)
print('2-D array : ' , twoD)
print('3rd column of 1st two rows : ' , twoD[0:3,2:3])

2-D array :  [[0 1 2 3 4]
 [5 6 7 8 9]]
3rd column of 1st two rows :  [[2]
 [7]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [235]:
arr = np.random.rand(10,10)
print('min value: ', np.amin(arr), ', max value: ', np.amax(arr))

min value:  0.033172082646683254 , max value:  0.9967260968029398


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [7]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print( 'common items : ', np.intersect1d(a,b))

common items :  [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [14]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a==b))

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [20]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != 'Will']

array([[-1.34476238,  1.21574677,  1.58933738, -1.86529729],
       [-0.94524963, -0.8989917 , -0.1334427 , -1.77650665],
       [-0.16846302, -0.55027466,  0.99289582,  0.97341589],
       [-0.51197148, -0.22557753,  0.94881799,  0.80620214],
       [-0.34034252,  0.21617078, -1.67510291, -0.22287049]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [22]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[(names != 'Will') & (names != 'Joe')]

array([[ 0.64858325, -1.38756044,  0.24429927,  1.7140062 ],
       [ 0.81977934,  2.08455898,  0.30099473,  1.36481899]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [26]:
print(np.random.uniform(1,15, size=(5,3)))

[[ 2.54227247 11.31726714  4.52105396]
 [ 8.24708581  9.39693453  9.16968276]
 [13.77410697  1.4830315   8.58380036]
 [11.18544846 10.38685576 12.32869328]
 [ 9.1073414  10.717895    7.14436287]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [29]:
arr = np.random.uniform(1,16, size=(2, 2, 4))
print(arr)

[[[15.94178228  2.25758212 10.62275203  5.75345209]
  [14.65091028  1.2317948  14.50086548 14.98517602]]

 [[10.94330323  3.89268754 13.84162382  4.58871578]
  [ 9.8725415   9.49549965 10.84551463  2.22089167]]]


33. Swap axes of the array you created in Question 32

In [37]:
#T=Transpose , can use any
print(arr.T)

[[[15.94178228 10.94330323]
  [14.65091028  9.8725415 ]]

 [[ 2.25758212  3.89268754]
  [ 1.2317948   9.49549965]]

 [[10.62275203 13.84162382]
  [14.50086548 10.84551463]]

 [[ 5.75345209  4.58871578]
  [14.98517602  2.22089167]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [41]:
arr = np.sqrt([np.random.rand(10)])
arr[arr < 0.5] = 0
print(arr)

[[0.         0.         0.64480703 0.         0.         0.
  0.         0.73464684 0.62484343 0.85830876]]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [48]:
arr1 = np.random.rand(12)
arr2 = np.random.rand(12)
print (arr1)
print (arr2)
print ( 'Max values b/w 2 arrays: ', np.maximum(arr1, arr2) )

[0.29310217 0.38008885 0.11029557 0.45847393 0.5031138  0.91782263
 0.03625361 0.53150028 0.54773275 0.91345235 0.02765719 0.26124271]
[0.15760971 0.71929096 0.84197679 0.51397317 0.43994985 0.90381994
 0.95107367 0.08078803 0.47372668 0.96746195 0.98775009 0.65780723]
Max values b/w 2 arrays:  [0.29310217 0.71929096 0.84197679 0.51397317 0.5031138  0.91782263
 0.95107367 0.53150028 0.54773275 0.96746195 0.98775009 0.65780723]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [53]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print( np.sort (np.unique(names) ) )

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [57]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
print ( a [~np.in1d(a, b)] )

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = np.array([[10,10,10]])


In [62]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:,1] = newColumn[:,0]
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [65]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print( np.dot( x,y ) )

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [68]:
print ( np.cumsum (np.random.rand(20)) )

[ 0.57752098  1.50217063  2.20050483  2.62080345  3.42768728  4.21540244
  4.32256348  4.88130952  5.67206365  6.41589875  6.77672177  7.76236871
  8.53618138  8.93406682  9.33827646  9.88679191 10.10270794 11.06178299
 11.36835586 12.32580062]


41. Stack arrays a and b vertically

---
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [87]:
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)
print (a)
print (b)
print ( np.vstack((a,b)) )

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


42. Stack arrays a and b horizontally

---
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [88]:
a = np.arange(10).reshape(2,-1) 
b = np.repeat(1, 10).reshape(2,-1)
print (a)
print (b)
print ( np.hstack((a,b)) )

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


43. Create array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]) without hardcod, by using numpy functions and array a.

---
a = np.array([1,2,3])

In [91]:
a = np.array([1,2,3])
solution_array = np.hstack((np.repeat(a, 3), a, a, a))
print(solution_array)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


44. Arithmetic Operators

In [100]:
num = 7

print('Add 1 in number : ' , num + 1) 
print('Subtract 1 from number : ' , num - 1) 
print('Multiply number with 2 : ' , num * 2) 
print('Divid by number by 2 : ' , num / 2) 
print('Exponent of 2 : ' , num ** 2) 

Add 1 in number :  8
Subtract 1 from number :  6
Multiply number with 2 :  14
Divid by number by 2 :  3.5
Exponent of 2 :  49


45. Logical Operators

In [118]:
a = [2,3,4]
b = [2,'f',4]
t = True
f = False
print('Logical AND : ', [a and b], ' , ', t and f)

print('\nLogical OR : ', [a or b], ' , ', t or f)

print('\nLogical NOT : ', not t)

print('\nLogical XOR : ', t != f)

Logical AND :  [[2, 'f', 4]]  ,  False

Logical OR :  [[2, 3, 4]]  ,  True

Logical NOT :  False

Logical XOR :  True


46. Print  zeros


In [119]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


47. print zeros with 2 rows and 3 columns

In [120]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


48. Print first, last and 2nd position of array

In [128]:
 num = np.array([5,15,25,35]) 
print('First position: ',num[0]) 
print('\nLast position: ',num[3])
print('\n2nd position: ',num[1]) 

First position:  5

Last position:  35

2nd position:  15


49. Create a 8x8 matrix and fill it with a checkerboard pattern

In [130]:
arr = np.ones((3,3))
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


50.  Create a 2d array with 1 on the border and 0 inside. 


In [131]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
