# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [6]:
nullVctr = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [46]:
rangeVctr = np.arange(10,49)

4. Find the shape of previous array in question 3

In [12]:
print('shape of array ', rangeVctr.shape)

shape of array  (39,)


5. Print the type of the previous array in question 3

In [17]:
print(rangeVctr.dtype)

int32


6. Print the numpy version and the configuration


In [21]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/HP/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C

7. Print the dimension of the array in question 3


In [22]:
print(rangeVctr.ndim)

1


8. Create a boolean array with all the True values

In [31]:
print('Boolean array with true values : ' , np.ones(10, dtype=bool))


Boolean array with true values :  [ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [41]:
print(np.ones((2,2)))
# print([[0]*2]*2)

[[1. 1.]
 [1. 1.]]


10. Create a three dimensional array



In [42]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [49]:
rangeVctr = np.arange(10,49)
print('vector : ', rangeVctr)
print('Reversed vector : ', np.flip(rangeVctr))

vector :  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
Reversed vector :  [48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [50]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [54]:
print('3x3 Identity matrix : ')
print( np.identity(3))

3x3 Identity matrix : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [61]:
arr = np.array([1, 2, 3, 4, 5])
floatArry = arr.astype('float64')
print(floatArry.dtype)

float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [70]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
print(np.multiply(arr1, arr2))
#print(arr1 * arr2)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [77]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

print((arr1 == arr2).all())

False


17. Extract all odd numbers from arr with values(0-9)

In [89]:
oddArr = np.arange(10)[np.arange(10) % 2 ==1]
print('Odd numbers : ' , oddArr)

Odd numbers :  [1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [107]:
x = np.arange(10)

x[x % 2 == 1] = -1
print(x)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [115]:
x = np.arange(10)
x [ (x > 4) & (x < 9)] = 12
print(x)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [131]:
x = np.ones((7,7))
x[1:-1 , 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [135]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
print(np.where(arr2d == 5,12, arr2d))

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [174]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                  [[7, 8, 9], [10, 11, 12]]])

arr3d[0,:-1] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [217]:
twoD = np.arange(10).reshape(2,5)
print('2-D array : ' , twoD)
print('1st 1-D array' , twoD[0])


2-D array :  [[0 1 2 3 4]
 [5 6 7 8 9]]
1st 1-D array [0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [219]:
twoD = np.arange(10).reshape(2,5)
print('2-D array : ' , twoD)
print('2nd 1-D array' , twoD[1])

2-D array :  [[0 1 2 3 4]
 [5 6 7 8 9]]
2nd 1-D array [5 6 7 8 9]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [230]:
twoD = np.arange(10).reshape(2,5)
print('2-D array : ' , twoD)
print('3rd column of 1st two rows : ' , twoD[0:3,2:3])

2-D array :  [[0 1 2 3 4]
 [5 6 7 8 9]]
3rd column of 1st two rows :  [[2]
 [7]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [235]:
arr = np.random.rand(10,10)
print('min value: ', np.amin(arr), ', max value: ', np.amax(arr))

min value:  0.033172082646683254 , max value:  0.9967260968029398


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [239]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print( 'common items : ', np.intersect1d(a,b))

common items :  [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [254]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
d =np.ndindex(b)
print(d)


TypeError: only integer scalar arrays can be converted to a scalar index

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

33. Swap axes of the array you created in Question 32

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


40. Generate a matrix of 20 random values and find its cumulative sum