**Support Vector Machine**
- Supervised Learning Model
- used to analyze data for classification and regression analysis
- 
**Hyper Plane**
- n dimension plane

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import svm

df = pd.read_csv('messidor_features.csv')
df.shape
df.head()

X = df.drop('Class', axis=1)
y = df['Class']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

y_pred = svclassifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[91 17]
 [43 80]]
              precision    recall  f1-score   support

           0       0.68      0.84      0.75       108
           1       0.82      0.65      0.73       123

    accuracy                           0.74       231
   macro avg       0.75      0.75      0.74       231
weighted avg       0.76      0.74      0.74       231



In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

file = 'messidor_features.csv'

# Assign colum names to the dataset
colnames = ['p', 'ps', 'nma.a', 'nma.a', 'nma.b', 'nma.c', 'nma.d', 'nma.e', 'nma.f', 'nex.a', 'nex.b', 'nex.c', 'nex.d', 'nex.e', 'nex.f', 'nex.g', 'nex.h', 'dd', 'dm', 'Class']

# Read dataset to pandas dataframe
data = pd.read_csv('messidor_features.csv')

X = data.drop('Class', axis=1)
y = data['Class']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=10)
svclassifier.fit(X_train, y_train)

y_pred = svclassifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[97  7]
 [85 42]]
              precision    recall  f1-score   support

           0       0.53      0.93      0.68       104
           1       0.86      0.33      0.48       127

    accuracy                           0.60       231
   macro avg       0.70      0.63      0.58       231
weighted avg       0.71      0.60      0.57       231



In [3]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

y_pred = svclassifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[90 14]
 [62 65]]
              precision    recall  f1-score   support

           0       0.59      0.87      0.70       104
           1       0.82      0.51      0.63       127

    accuracy                           0.67       231
   macro avg       0.71      0.69      0.67       231
weighted avg       0.72      0.67      0.66       231



In [4]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

y_pred = svclassifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[34 70]
 [65 62]]
              precision    recall  f1-score   support

           0       0.34      0.33      0.33       104
           1       0.47      0.49      0.48       127

    accuracy                           0.42       231
   macro avg       0.41      0.41      0.41       231
weighted avg       0.41      0.42      0.41       231



**Neural Network**

In [5]:
import tensorflow as tf
tf.__version__

'2.4.0'

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

df=pd.read_csv('messidor_features.csv')
df.head()

0  1   2   3   4   5   6   7          8          9         10        11  \
0  1  1  22  22  22  19  18  14  49.895756  17.775994   5.270920  0.771761   
1  1  1  24  24  22  18  16  13  57.709936  23.799994   3.325423  0.234185   
2  1  1  62  60  59  54  47  33  55.831441  27.993933  12.687485  4.852282   
3  1  1  55  53  53  50  43  31  40.467228  18.445954   9.118901  3.079428   
4  1  1  44  44  44  41  39  27  18.026254   8.570709   0.410381  0.000000   

         12        13        14        15        16        17  18  Class  
0  0.018632  0.006864  0.003923  0.003923  0.486903  0.100025   1      0  
1  0.003903  0.003903  0.003903  0.003903  0.520908  0.144414   0      0  
2  1.393889  0.373252  0.041817  0.007744  0.530904  0.128548   0      1  
3  0.840261  0.272434  0.007653  0.001531  0.483284  0.114790   0      0  
4  0.000000  0.000000  0.000000  0.000000  0.475935  0.123572   0      1

In [7]:
X = df.iloc[:, :-1].values  # contains 1st 18 columns of df
y = df.iloc[:, 19].values   # labels

In [8]:
# to avoid overfitting divid dataset into train and test
 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [9]:
# scale the features

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
# knn Algorithm

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 19)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=19)

In [11]:
y_pred = classifier.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.59      0.68      0.63       110
           1       0.66      0.56      0.61       121

    accuracy                           0.62       231
   macro avg       0.62      0.62      0.62       231
weighted avg       0.62      0.62      0.62       231

[[75 35]
 [53 68]]
0.6190476190476191


**Random Forest**

In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv('messidor_features.csv')

In [15]:
# get high level vide of df
df.head()

0  1   2   3   4   5   6   7          8          9         10        11  \
0  1  1  22  22  22  19  18  14  49.895756  17.775994   5.270920  0.771761   
1  1  1  24  24  22  18  16  13  57.709936  23.799994   3.325423  0.234185   
2  1  1  62  60  59  54  47  33  55.831441  27.993933  12.687485  4.852282   
3  1  1  55  53  53  50  43  31  40.467228  18.445954   9.118901  3.079428   
4  1  1  44  44  44  41  39  27  18.026254   8.570709   0.410381  0.000000   

         12        13        14        15        16        17  18  Class  
0  0.018632  0.006864  0.003923  0.003923  0.486903  0.100025   1      0  
1  0.003903  0.003903  0.003903  0.003903  0.520908  0.144414   0      0  
2  1.393889  0.373252  0.041817  0.007744  0.530904  0.128548   0      1  
3  0.840261  0.272434  0.007653  0.001531  0.483284  0.114790   0      0  
4  0.000000  0.000000  0.000000  0.000000  0.475935  0.123572   0      1

In [16]:
#scale the data 

X = df.iloc[:,0:19].values  # attributes
y = df.iloc[:,19].values      # labels

In [17]:
# train the dataset

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [18]:
# feature scaling

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [19]:
# RF classifier

from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators = 20, random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[68 33]
 [43 87]]
0.670995670995671


**SVM**

In [21]:
# import dependencies
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [22]:
# import dataset
df = pd.read_csv('messidor_features.csv')

In [23]:
# Explanatory data analysis
df.shape
df.head()

0  1   2   3   4   5   6   7          8          9         10        11  \
0  1  1  22  22  22  19  18  14  49.895756  17.775994   5.270920  0.771761   
1  1  1  24  24  22  18  16  13  57.709936  23.799994   3.325423  0.234185   
2  1  1  62  60  59  54  47  33  55.831441  27.993933  12.687485  4.852282   
3  1  1  55  53  53  50  43  31  40.467228  18.445954   9.118901  3.079428   
4  1  1  44  44  44  41  39  27  18.026254   8.570709   0.410381  0.000000   

         12        13        14        15        16        17  18  Class  
0  0.018632  0.006864  0.003923  0.003923  0.486903  0.100025   1      0  
1  0.003903  0.003903  0.003903  0.003903  0.520908  0.144414   0      0  
2  1.393889  0.373252  0.041817  0.007744  0.530904  0.128548   0      1  
3  0.840261  0.272434  0.007653  0.001531  0.483284  0.114790   0      0  
4  0.000000  0.000000  0.000000  0.000000  0.475935  0.123572   0      1

In [24]:
# data preprocessing
X = df.drop('Class', axis=1) # attributes
y = df['Class']              # labels

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.20)

In [25]:
# training the algorithm
svcclassifier = SVC(kernel = 'linear')
svcclassifier.fit(X_train, y_train)

SVC(kernel='linear')

In [26]:
# prediction classes
y_pred = svcclassifier.predict(X_test)
print(y_pred)

[0 0 1 0 1 1 0 0 0 1 0 0 1 0 1 0 1 1 0 1 1 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0
 1 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 1 0 1
 0 1 0 0 0 1 0 1 1 1 1 0 0 0 1 1 0 0 1 1 1 0 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0
 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 1 1 0 1 1 1 0 0 1 1 1 0 1 1 0 0
 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 1 1 1 0 1 1 0 1 1 1 1 0 0 0 0 0 1 0 0 0 0 0
 1 0 0 1 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 1 1 1 0
 0 0 1 0 1 1 1 1 0]


In [27]:
# evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.67      0.75      0.71       110
           1       0.75      0.67      0.71       121

    accuracy                           0.71       231
   macro avg       0.71      0.71      0.71       231
weighted avg       0.71      0.71      0.71       231

[[83 27]
 [40 81]]
0.70995670995671


**ANN**

In [28]:
# import libraries
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [29]:
# importing dataset
df = pd.read_csv('messidor_features.csv')

In [30]:
# data preprocessing
X = df.iloc[:,:20]
y = df.iloc[:,0]

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [32]:
# training ANN
nn = MLPClassifier(activation='logistic', solver='sgd', hidden_layer_sizes=(10, 80), random_state =0)

In [33]:
nn.fit(X_train, y_train)

MLPClassifier(activation='logistic', hidden_layer_sizes=(10, 80),
              random_state=0, solver='sgd')

In [34]:
# predict values
y_pred = nn.predict(X_test)
print(y_pred)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1]


In [35]:
# evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.99      1.00      1.00       229

    accuracy                           0.99       231
   macro avg       0.50      0.50      0.50       231
weighted avg       0.98      0.99      0.99       231

[[  0   2]
 [  0 229]]
0.9913419913419913


C:\Users\HP\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
